### ISSUE TITLE
Allow for custom API key

### ISSUE THREAD

**Issue by ggraham-phs** [jmarshallnz/statsNZ#1]
Kia ora, 

Great to see this being put together.

I recommend adjusting the functions so that the user must provide the api key, instead of using the one hardcoded into the function

**Comment by jmarshallnz** [comment]
Good suggestion, but a quick look shows that StatsNZ has changed their API setup in the last 5 years, so this is no longer relevant!

I'm sure that the package could be adapted to the new API (and this would be useful!) - see here for some existing R code for example:

https://github.com/StatisticsNZ/open-data-api/blob/main/R/get-data-from-stats-api.R

Potentially the best approach might just be to get started based on that code, as the code here won't work anymore. :)

**Comment by ggraham-phs** [comment]
That sounds like a good idea, I'll pursue that. Haha I hadn't thought to check when this was last updated.
